// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace RazorPages.Migrations
{
    [DbContext(typeof(RazorPagesContext))]
    partial class RazorPagesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("RazorPages.Models.Courier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<int?>("RegionId")
                        .HasColumnType("integer")
                        .HasColumnName("region_id");

                    b.HasKey("Id")
                        .HasName("pk_courier");

                    b.HasIndex("RegionId")
                        .HasDatabaseName("ix_courier_region_id");

                    b.ToTable("courier");
                });

            modelBuilder.Entity("RazorPages.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.HasKey("Id")
                        .HasName("pk_customer");

                    b.ToTable("customer");
                });

            modelBuilder.Entity("RazorPages.Models.Dish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("DishsOfOrderId")
                        .HasColumnType("integer")
                        .HasColumnName("dishs_of_order_id");

                    b.Property<int?>("MenuId")
                        .HasColumnType("integer")
                        .HasColumnName("menu_id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<string>("SpeedOfCooking")
                        .HasColumnType("text")
                        .HasColumnName("speed_of_cooking");

                    b.Property<string>("TypeOfDish")
                        .HasColumnType("text")
                        .HasColumnName("type_of_dish");

                    b.HasKey("Id")
                        .HasName("pk_dish");

                    b.HasIndex("DishsOfOrderId")
                        .HasDatabaseName("ix_dish_dishs_of_order_id");

                    b.HasIndex("MenuId")
                        .HasDatabaseName("ix_dish_menu_id");

                    b.ToTable("dish");
                });

            modelBuilder.Entity("RazorPages.Models.DishsOfOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.HasKey("Id")
                        .HasName("pk_dishs_of_order");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_dishs_of_order_order_id");

                    b.ToTable("dishs_of_order");
                });

            modelBuilder.Entity("RazorPages.Models.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("RestrantId")
                        .HasColumnType("integer")
                        .HasColumnName("restrant_id");

                    b.HasKey("Id")
                        .HasName("pk_menu");

                    b.HasIndex("RestrantId")
                        .HasDatabaseName("ix_menu_restrant_id");

                    b.ToTable("menu");
                });

            modelBuilder.Entity("RazorPages.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.HasKey("Id")
                        .HasName("pk_order");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_order_customer_id");

                    b.ToTable("order");
                });

            modelBuilder.Entity("RazorPages.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("RestrantId")
                        .HasColumnType("integer")
                        .HasColumnName("restrant_id");

                    b.HasKey("Id")
                        .HasName("pk_region");

                    b.HasIndex("RestrantId")
                        .HasDatabaseName("ix_region_restrant_id");

                    b.ToTable("region");
                });

            modelBuilder.Entity("RazorPages.Models.Restrant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.HasKey("Id")
                        .HasName("pk_restrant");

                    b.ToTable("restrant");
                });

            modelBuilder.Entity("RazorPages.Models.Courier", b =>
                {
                    b.HasOne("RazorPages.Models.Region", null)
                        .WithMany("CouriersOfRestrant")
                        .HasForeignKey("RegionId")
                        .HasConstraintName("fk_courier_region_region_id");
                });

            modelBuilder.Entity("RazorPages.Models.Dish", b =>
                {
                    b.HasOne("RazorPages.Models.DishsOfOrder", null)
                        .WithMany("DishesOfOrder")
                        .HasForeignKey("DishsOfOrderId")
                        .HasConstraintName("fk_dish_dishs_of_order_dishs_of_order_id");

                    b.HasOne("RazorPages.Models.Menu", null)
                        .WithMany("MyProperty")
                        .HasForeignKey("MenuId")
                        .HasConstraintName("fk_dish_menu_menu_id");
                });

            modelBuilder.Entity("RazorPages.Models.DishsOfOrder", b =>
                {
                    b.HasOne("RazorPages.Models.Order", "OrderOfList")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .HasConstraintName("fk_dishs_of_order_order_order_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderOfList");
                });

            modelBuilder.Entity("RazorPages.Models.Menu", b =>
                {
                    b.HasOne("RazorPages.Models.Restrant", "RestrantOfMenu")
                        .WithMany()
                        .HasForeignKey("RestrantId")
                        .HasConstraintName("fk_menu_restrant_restrant_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RestrantOfMenu");
                });

            modelBuilder.Entity("RazorPages.Models.Order", b =>
                {
                    b.HasOne("RazorPages.Models.Customer", "CustomerOfDish")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("fk_order_customer_customer_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerOfDish");
                });

            modelBuilder.Entity("RazorPages.Models.Region", b =>
                {
                    b.HasOne("RazorPages.Models.Restrant", "RestrantOfMenu")
                        .WithMany()
                        .HasForeignKey("RestrantId")
                        .HasConstraintName("fk_region_restrant_restrant_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RestrantOfMenu");
                });

            modelBuilder.Entity("RazorPages.Models.DishsOfOrder", b =>
                {
                    b.Navigation("DishesOfOrder");
                });

            modelBuilder.Entity("RazorPages.Models.Menu", b =>
                {
                    b.Navigation("MyProperty");
                });

            modelBuilder.Entity("RazorPages.Models.Region", b =>
                {
                    b.Navigation("CouriersOfRestrant");
                });
#pragma warning restore 612, 618
        }
    }
}
